// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABpYKXLQKCZZ4fGoH-18IqsWClGWoebeg',
    appId: '1:1469856911:web:af63ffda43f52a978304fa',
    messagingSenderId: '1469856911',
    projectId: 'blazesense-8d788',
    authDomain: 'blazesense-8d788.firebaseapp.com',
    storageBucket: 'blazesense-8d788.firebasestorage.app',
    measurementId: 'G-STQ16JH58G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpHck74EMwlJNwR_-SPmM0lcqDhr2PQcc',
    appId: '1:1469856911:android:3b65e0326531931c8304fa',
    messagingSenderId: '1469856911',
    projectId: 'blazesense-8d788',
    storageBucket: 'blazesense-8d788.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkYoG-xLUfdy0D7-sHhfJqgjKAcd4w7oQ',
    appId: '1:1469856911:ios:ecf16f62321ae5d68304fa',
    messagingSenderId: '1469856911',
    projectId: 'blazesense-8d788',
    storageBucket: 'blazesense-8d788.firebasestorage.app',
    iosBundleId: 'com.flutterilk.flutterilk',
  );
}
